spring:
  datasource:
    generate-unique-name: false
    name: AntiCafe
reserve:
  service:
    daysToReserve: 7
    openingHour: 9
    closingHour: 24
scheduler:
  order:
    lifetime:
      tagged-deletion: 2