spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: qwe
    password: qwe
reserve:
  service:
    daysToReserve: 7
    openingHour: 9
    closingHour: 24
scheduler:
  order:
    lifetime:
      tagged-deletion: 2
page:
  page: 10
